### ISSUE TITLE
Blank pages during navigations

### ISSUE THREAD

**Issue by jordanperr** [NREL/NEB-Tool#77]
To test edge cases for navigations on both **local host** and **cloud host** to ensure robustness.

- [ ] Navigate to url like "/setup-wizard/company-kpi" should redirect to the homepage (potentially display an error before redirecting)
- [ ] Refreshing any page should reload the app to the same page.

-----------------------------------------------------------------------------------------
There are a couple cases i've noticed where a blank page is shown to the user.

- Navigating directly to the page "https://gray-tree-06c66911e.4.azurestaticapps.net/setup-wizard/company-kpi" without first initializing the setup wizard results in a blank page. I would prefer it redirect to the homepage in these cases.
- Refreshing any page in the setup wizard, such as "https://gray-tree-06c66911e.4.azurestaticapps.net/setup-wizard/facility-setup" results in a blank page. I would prefer it reload the app to the same page, with the same data filled in.

There may be more ways to trigger this bug.

**Comment by rmroot** [comment]
This should be resolved with the data saving issue implemented.

**Comment by jordanperr** [comment]
Still happening for me in Safari and Firefox. Reset your database and then visit the following URL:
https://gray-tree-06c66911e.4.azurestaticapps.net/setup-wizard/company-kpi

**Comment by rmroot** [comment]
I've put in guards to prevent errors from occuring in this scenario and the proper navigatio occurs when running on localhost. I think this may have something to do with the gray tree host. It is popping up errors about loading html
<img width="529" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBODBsQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ebe3852dd591947723ae502ffc590ecf81a35f35/Screenshot%202024-05-30%20at%203.45.09%E2%80%AFPM.png" alt="Screenshot 2024-05-30 at 3.45.09 PM.png" />


it's strange because that route (/setup-wizard/company-kpi) should trigger the 404 error page but it is not triggering it.

I'm not gonna spend too much additional time on this at the moment. After the PR gets merged in we can move the issue to the backlog and look further into what is happening if it's still occurring on the production hosted application.

**Comment by RLiNREL** [comment]
moving back to product log. We can resume this during the testing and feedback phase.
To test navigating to url without initializing setup wizard and refreshing the page both locally and on cloud host.

**Comment by rmroot** [comment]
This took some updates to the angular application and the server hosting the application. dev.justifi.ornl.gov is updated with the changes and no longer seeing this issue. closing
